version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_iwellness
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db_iwellness}
      MYSQL_USER: ${MYSQL_USER:-iwellness_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-iwellness_password}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tesisNetwork

networks:
  tesisNetwork:
    external: true

volumes:
  mysql_data: